markdown: kramdown
highlighter: null
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Brandon Williams
production_url : https://williamsbdev.com
description: "Vim, Unix, Python, Ember.js, JavaScript"
disqus_shortname: williamsbgithubio
author :
  name : Brandon Williams
  github : williamsbdev
  twitter: williamsbdev
  email: williamsbdev@gmail.com
