markdown: redcarpet
pygments: true
permalink: /posts/:title
rdiscount:
  extensions: [smart]
title : Brandon Williams
production_url : http://williamsbdev.com
description: "Ember.js, JavaScript, Vim, Python, Shell"
disqus_shortname: williamsbgithubio
author :
  name : Brandon Williams
  github : williamsbdev
  twitter: williamsbdev
  email: williamsbdev@gmail.com
